# Generated by Django 5.0.6 on 2024-05-29 08:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('cycle', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='용돈 주기')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='용돈 금액')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'verbose_name': '용돈 정보',
                'verbose_name_plural': '용돈 정보 목록',
                'db_table': 'allowance',
            },
        ),
        migrations.CreateModel(
            name='AllowanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=6, verbose_name='용돈 분류')),
                ('icon', models.CharField(max_length=16, verbose_name='용돈 분류 아이콘')),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bank.allowance', verbose_name='용돈 정보')),
            ],
            options={
                'verbose_name': '용돈 분류',
                'verbose_name_plural': '용돈 분류 목록',
                'db_table': 'allowance_category',
            },
        ),
    ]
